### PR TITLE
Remove the need to change the dev and demo config 

### PR DESCRIPTION
**Pull request by msl8r**
### Change description ###
Remove the need to change the dev and demo config when clusters are swapped over

Copying over work done in https://github.com/hmcts/aks-cft-deploy/pull/313

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Review by timja — APPROVED** [review]
thanks

**Comment by JayDoubleu** [comment]
Nice one @msl8r , should we also add this to CFT ?

**Comment by msl8r** [comment]
> Nice one @msl8r , should we also add this to CFT ?

Already done @JayDoubleu check my comment 

> Copying over work done in https://github.com/hmcts/aks-cft-deploy/pull/313

**Comment by JayDoubleu** [comment]
Ahh of course. Apologies.. I've missed that

**Pull request merged**
